{
    'name': 'EcoSphere ESG Management',
    'version': '17.0.1.0.0',
    'summary': 'Environmental, social and governance management platform',
    'category': 'Human Resources/ESG',
    'author': 'EcoSphere',
    'license': 'GPL-3',
    'depends': ['base', 'mail', 'hr', 'purchase', 'stock', 'account'],
    'data': [
        'security/esg_security.xml',
        'security/ir.model.access.csv',
        'data/esg_sequence_data.xml',
        'data/esg_mail_template_data.xml',
        'data/esg_cron_data.xml',
        'views/esg_views.xml',
        'wizard/esg_report_builder_wizard_views.xml',
        'reports/esg_report_actions.xml',
        'reports/esg_report_templates.xml',
        'views/esg_menus.xml',
    ],
    'assets': {'web.assets_backend': ['esg_management/static/src/js/esg_dashboard.js', 'esg_management/static/src/xml/esg_dashboard.xml', 'esg_management/static/src/css/esg_dashboard.css']},
    'application': True,
    'installable': True,
    'auto_install': False,
}
